version: "3.8"

services:
  users:
    build:
      context: .
      dockerfile: ./users/Dockerfile.dev
    env_file:
      - ./users/.env
    volumes:
      - ./users:/app
      - ./common:/common
    ports:
      - "3001:3000"
    depends_on:
      - users-db
      - amqp

  mail:
    build:
      context: .
      dockerfile: ./mail/Dockerfile.dev
    env_file:
      - ./mail/.env
    volumes:
      - ./mail:/app
      - ./common:/common
    depends_on:
      - amqp

  users-db:
    image: mongo
    ports:
      - "20000:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=doclinker
      - MONGO_INITDB_ROOT_PASSWORD=doclinker
    volumes:
      - ./.volumes/users-db:/data/db

  amqp:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=doclinker
      - RABBITMQ_DEFAULT_PASS=doclinker
