version: '3.8'

services:
  users:
    build: 
      context: .
      dockerfile: ./users/Dockerfile
    env_file:
      - ./users/.env
    ports:
      - "3001:3000"

  amqp:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=docspot
      - RABBITMQ_DEFAULT_PASS=docspot